org: refdudu
app: puppeteer
service: puppeteer
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  # runtime: nodejs14.x
  memorySize: 1024
  timeout: 60

functions:
  screenshot:
    handler: src/screenshot.handler
  create-pdf:
    handler: src/create-pdf.handler
