org: refdudu
app: aws-lambda
service: aws-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  timeout: 60

functions:
  screenshot:
    handler: src/screenshot.handler
  create-pdf:
    handler: src/create-pdf.handler
