org: refdudu
app: aws-lambda
service: aws-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  screenshot:
    handler: src/screenshot.handler
  create-document-pdf:
    handler: src/create-document-pdf.handler
    environment:
      bucket: storage-2024-05-22
